CMS_HOST: studio.local.overhang.io
CMS_OAUTH2_SECRET: cUdmXBEXTNBTPl3iGCsYc5EC
CONTACT_EMAIL: contact@local.overhang.io
ENABLE_HTTPS: false
ID: cBk47GAwvwkNA7OfZNp97Uc4
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEAnTi4vf8k4pTS8Z1bDHQfKZxaLH3s0QQWaBMzAaaF2FKhPYvD

  1euhXvgEkYLFq8YsYnUHGT0cd+urdB6DxFXeG6xrb0IfHkXVMqMu6omUxIEYR61z

  K/Y1ndewCEv8jjGRZ4gFZBn3h7z93z8+IQJ+9NN8ZQbozui2UU4HoiFEKQhfXki5

  WWoLv+79awK/A2qgGTy3rUZBtH7iST45eAUWCKJAyNCt5yfdcDoNPcXB/Rdt8sk3

  Crgsqr9RWawHTAWkcUcVfEkDSpm8nTjJd7hmuMx9gp/P5xv1voxmYU3JCvlVH+uR

  F8E1VXJUvv+cAdBjhk/X0Xj4P+II4iiq0oBJcQIDAQABAoIBAARAWpKHWeEnTWr2

  KoD0NObZplXp/njfx5ap35O4WTSHy3oQE6FvEo6Fs2NB6i7NGDnTWKKglJVTke/S

  ZsAXjal+6JV6GsBP+sYN7pYDVrqs6PyrM+A+SKXg2rmRYHNx41uC10PP20ctiknl

  T7yccNVq+0P6GK/bpW5zvItwTdkJfjpwcJrBLwJAvww2DXU2bYN2gPCoNUKNPweR

  VLJJKISdh+lB0BL+hhia2+P8iOObqV0QpKojU34Kli9e28usWSe6U01jkFwPQdHh

  ns4J1/Kbu8YkH3oSpP3cE4Ez0Iq18eHM2MA5g7cTnyGQKTjwlrxFfZhbAQCxngAJ

  rDBp63cCgYEAwAtv1KF7j6NrW7OTbkqyKj2OipLckDIVPfQl7vIw8/j2lQS+LHYE

  Rvs7qVNviAA/mdsTWT4XRRkrJjlko4fUq8fAU4breW9H4enRIoB/sbtSPgRiE2JV

  zOZumvnKMBTZF2f1QUjxg9FqbHigzFn/Hz12s4+BE8gQ4l85QEHXhVcCgYEA0ZR6

  abXRxbJf3Ajku8weROdCKUakpLYs1psanMYJReUY4DXANtWR5A80+KGKtMEs6smh

  iYROO5zuZYpmR38e3e1HbvYt4Vrn109m4QOZZe554TrLjQ+H0Ud7a+1IQ1fy2C3H

  9UWWhYoxoAUts/pH6XdOaTWgioorbnPENxoqYncCgYBmWPIFgPYn6/D4UzDcU6S2

  DE5eHby8gGR/uxFIUfyy2VkYvAlaCp9m8Nev+w5yjadXqMCcDBI8uhgb6/RtjqNR

  1Ufze/Ecq6jEhmb1m0PyhaFj+dQG/p45cAk8QKl3jHTSG45Cd8x28vFj07nmjoP/

  szMCqRUiZLpS2mrZiv2ASwKBgAiGi7xFIzVxniirS/K/yPNwnOZk80moB4brZFfA

  TpxDR5HHXfxdD8RBQhxjJetYeGVMsn+PnEcciS4kRSjfaPgKMP+4kAE823WMy1iX

  9uOIofihlao1WYcP61tmmavzpfNZWWsG26qvBnnF/Cf4JHjA27W38sHwAPhLSU4c

  iGDdAoGAGVX64jWr4+MNY7I8aVAc3Vj4EjLk3JOKG7L021osuP9jRd+jCihpN5Nd

  nXVd5VUMkcz9rckDXbYDgKq6hENLQLC9sUgAB4K+4mSSUO9EV5K08FMbHymh/0UT

  nOXwK096W5gGzvQWhojX7ZoaUDoz1rhctlM5sEYR/AI7a8TQLPg=

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.overhang.io
MYSQL_ROOT_PASSWORD: V3peoYnf
OPENEDX_MYSQL_PASSWORD: s4UKEAki
OPENEDX_SECRET_KEY: 7S9loF7z1Nw9bRs0YGIPnbSy
PLATFORM_NAME: My Open edX
PLUGINS: []
